language: node_js
sudo: false
compiler:
  - gcc
node_js:
- '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- pip install --user cpp-coveralls
install:
- npm install
- npm install coveralls
script:
- ./configure --enable-gcov && make && make check
- npm run coverage
after_success:
- npm run coveralls --exclude tests --gcov-options '\-lp'
cache:
  directories:
    - node_modules
